# Native resolver config (secrets in Windows Credential Manager)
host=bw-overlay-service-lolcor33.l.aivencloud.com
port=14338
databaseName=defaultdb
user=avnadmin
sslMode=REQUIRED
caCert=-----BEGIN CERTIFICATE----- MIIERDCCAqygAwIBAgIUSfbtAMN+XhvVYKFcQ/bjb5LhvXMwDQYJKoZIhvcNAQEM BQAwOjE4MDYGA1UEAwwvOGZmNGRiNTgtYzY3Yi00MzJiLWE4ODMtZjUxMmFmNTkw OTRkIFByb2plY3QgQ0EwHhcNMjYwMzExMTAzODQxWhcNMzYwMzA4MTAzODQxWjA6 MTgwNgYDVQQDDC84ZmY0ZGI1OC1jNjdiLTQzMmItYTg4My1mNTEyYWY1OTA5NGQg UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALoL1TJS tUF6r1+4MbQ0XRokVCaFPAGPmx4E3JAkgNRsZG7uTpZD/6vD1A7K+w0Xss9KNKXt +bH/d5iWH/xQZJD/FzcZYJS6rCp1AhvwsgfTi848t7WgYPtv71tuU9gnFO/bMfxt IGpdt/bYSzKgDG9dvvEcqhCKWhciXdyEDrDNelG45kYC3X6pVEy36eIApufIEWFZ /fq53Dh92Z2FepZDXxKlQbz3ztXt3HhIWMvBXCMR0xYak8+UZu48YRCJiz8my+Hl my0wVVl6agNyvSjWoQ3ipwJYcQzOCt05M6xou2IAcqlM+V87M0U2Qe+79km6T2AL OHM529PGDuQyjoMZNoXDbM+Y/hrSfEEiMaNXAUpRVMDZ1Eo1jwXpv7m8J43wWSwS 6UIAzV2gJxrwEPaYDY16DMEs1DTt28wM5aeLsWz61b+kSo0eN4Jh7PfwCSGbWjID oshwl46L0u7IbTXyUj16M5J0xVmbTbWlId4thlQo+9gVNcd8LCDSeLufcwIDAQAB o0IwQDAdBgNVHQ4EFgQUtA2IHyYn+iG/KPgMZi9dsUU5huYwEgYDVR0TAQH/BAgw BgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBADyZaKUgmWHP yII+JG8Xr6dMaqURPv7fla4blj5yCUsJrh8rsThpnMLotyYxqp25lqvAvXBUqAjo U1DWD3uB4ka/mpyEgxV90NnSTxCqfgKySyOlW07UVGgURN21zvgKfkNhGdKx7lEq M96d02qDyM3K3FcEkt7Ya5kxOnMvExXBhEn/sY+EiCtg/mLRQvnq9uQVjA4IZQkL lBEkj6J9J+KVd3gYxzKDuIUWbkNm+0i24SeL8RLp64FxYnNkE6aoEj8bLLOGF1ri r9IzN8eIoPRLmFHrzMoSECKG/u9TZwmidtTce2HuDDMVMAdfe0rv5N0ClJJIDxiK G38Uk52ix1F0EnyZw/3oa0sXHyhssdHNO13c/lbflf+zhVZKa1o//sdW/QTa7wQQ EtlnHDQIGPRSPhh0YNbElCTREs5xkrEH9s4v3cahmc0ns2jCFKRbC/jV78D4x6ZD MkzfJbw4k+xX9xkKEda326VjMlMGs0gxt+iqUgCXUEKin9CPCQ05zw\=\= -----END CERTIFICATE-----
resolver.bind=127.0.0.1
resolver.port=8787
resolver.table=pika_bedwars_monthly_wins
resolver.uuidColumn=offline_uuid
resolver.nameColumn=player_name
resolver.lastOnlineColumn=last_online
resolver.reportTable=pika_player_reports
resolver.requireSignature=true
resolver.signatureMaxSkewSec=30
resolver.secret.dbPasswordTarget=PikaResolver/DbPassword
resolver.secret.sharedSecretTarget=PikaResolver/SharedSecret
resolver.backend=native
resolver.enableJavaFallback=true
resolver.parityLog=false
